# Generated by Django 5.0.1 on 2026-05-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('crypto', 'Criptomonedas'), ('stocks', 'Acciones'), ('forex', 'Forex'), ('economy', 'Economía'), ('technology', 'Tecnología'), ('general', 'General')], default='general', max_length=20)),
                ('published_at', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('related_symbols', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-published_at'],
            },
        ),
    ]
