# Generated by Django 5.0.1 on 2026-05-30 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('crypto', 'Criptomoneda'), ('stock', 'Acción'), ('forex', 'Forex'), ('index', 'Índice'), ('commodity', 'Commodity')], max_length=20)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_change_pct_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('volume_24h', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('high_24h', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('low_24h', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('image_url', models.URLField(blank=True)),
                ('coingecko_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['rank', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('market', 'Mercado'), ('limit', 'Límite'), ('stop', 'Stop'), ('stop_limit', 'Stop Límite')], default='market', max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venta')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('filled', 'Ejecutada'), ('partially_filled', 'Parcialmente Ejecutada'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('alert_price_high', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('alert_price_low', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'asset')},
            },
        ),
    ]
